config/routes.rb
Cheftab::Application.routes.draw do
  devise_for :users
  resources :reports

  resources :restaurants

  resources :items
  resources :graphs, defaults: {format: 'json'}

  root to: 'pages#home'

  get 'pages/home'
  get 'static_pages/help'

  get '/home', to: 'pages#home', as: :home
  get '/help', to: 'pages#help', as: :help

  get '/restaurants/:id/connect', to: 'restaurants#connect'

  get '/restaurants/:id/devices/', to: 'restaurants#devices'

  get '/restaurants/:id/upload', to: 'restaurants#upload'

  get '/restaurants/:id/reports', to: 'restaurants#reports'

  get '/restaurants/:id/show', to: 'restaurants#show'

  get '/restaurants/:id/analyze', to: 'restaurants#analyze'

  get '/restaurants/:id/menu', to: 'restaurants#menu'

  get '/apitest' => 'reports#new'

  post '/reports/:user_id/:restaurant_id', to: 'reports#create'

  post '/restaurants/:id/new_item', to: 'restaurants#new_item'

  get '/contact', to: 'inquiry#index'

  get '/inquiry/send_mail', to: 'inquiry#send_mail'

  delete 'reports/:id', to: 'report#delete'

end

app/models/report.rb
class Report < ActiveRecord::Base
	has_one :restaurant
	has_one :user
	has_one :device
end

app/controllers/reports_controller.rb
require 'json'
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token


  respond_to :html
  respond_to :json

  def index
    redirect_to :home
  end

  def show
    respond_to do |format|
      format.html { render html: @report }
      format.json { render json: @report }
    end
  end

  def new
    @report = Report.new
    respond_with(@report)
  end

  def authenticate
    @api_key = params['key']
    @device = Device.where(api_key: api_key).first if @api_key

    unless @device
      head status: :unauthorized
      return false
    end
  end

  def edit
  end

  def create
    #@json = params["json"].gsub("\n", "").gsub("\r","").gsub(/  /, "")
    #@array = JSON.parse(@json)
    @array = params["reports"]
    @array.each do |e|
      #logger.debug e
      if Device.exists?(:id => params[:device_id])
        @device = Device.find(params[:device_id])
        @api_key = @device.api_key
      else
        @device = Device.create(:id => params[:device_id])
        @api_key = @device.api_key
      end

      @report = Report.create(:device_id => params[:device_id], :restaurant_id => params[:restaurant_id], :user_id =>params[:user_id], :when => DateTime.parse(e["when"]), :preptime => e["preptime"], :item => e["item"], :order_number => e["order_number"])
    end
    #flash[:notice] = "Entry added successfully"
    respond_to do |format|
      format.html { render html: @report }
      format.json { render json: @report }
    end
  end

  def update
    @report.update(report_params)
    respond_with(@report)
  end

  def destroy
    @report.destroy
    redirect_to :back
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:device, :date, :value, :restaurant_id, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
%form#test-add-form{:action => "/reports", :enctype => "multipart/form-data", :method => "POST"}
  .form-group
    %label{:for => "input-name"} URL
    %input.form-control{:name => "url", :readonly => "readonly", :type => "text", :value => "http://localhost:3000/reports/<user id>/<restaurant id>"}/
  .form-group
    %label User id:
    %input.form-control{:name => "user_id", :type => "text", :value => ""}/
  .form-group
    %label Restaurant id:
    %input.form-control{:name => "restaurant_id", :type => "text", :value => ""}/
  .form-group
    %label Device id:
    %input.form-control{:name => "device_id", :type => "text", :value => ""}/
  .form-group
    %label{:for => "input-name"} activities:
    %textarea.form-control{:cols => "120", :name => "json", :rows => "5"}
      :preserve
        [
          {"when": "2015-01-08 01:42:46 UTC", "preptime": 5490},
          {"when": "2015-01-09 01:42:46 UTC", "preptime": 2344},
          {"when": "2015-01-08 01:42:46 UTC", "preptime": 2779}
        ]  
  %button.btn.btn-success.btn-lg{:type => "submit"} Submit the Request

app/views/reports/edit.html.erb
<%- model_class = Report -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reports/edit.html.haml
- model_class = Report
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/reports/index.html.haml
- model_class = Report
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
- if flash[:notice]
  .notice= flash[:notice]
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:device_id)
      %th= model_class.human_attribute_name(:date)
      %th= model_class.human_attribute_name(:value)
      %th= model_class.human_attribute_name(:restaurant_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @reports.each do |report|
      %tr
        %td= link_to report.id, report_path(report)
        %td= report.device
        %td= report.date
        %td= report.value
        %td= report.restaurant_id
        %td= report.user_id
        %td= l report.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), |
            edit_report_path(report), :class => 'btn btn-mini'       |
          -#
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
            report_path(report),                                                                                         |
            :method => :delete,                                                                                          |
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
            :class => 'btn btn-mini btn-danger'                                                                          |
= link_to t('.new', :default => t("helpers.links.new")), |
  new_report_path,                                       |
  :class => 'btn btn-primary'                            |

app/views/reports/new.html.erb
<%- model_class = Report -%>
      
		  <div class="row-fluid">
		    <div class="span6">

		      <div class="page-header">
		        <h1>Adding a Report</h1>
		      </div>

		      <p>Adding a report is done through an HTTP URL in the following form:</p>

		      <pre>http://cheftab-demo.appspot.com/reports/&lt;user&gt;/&lt;restaurant&gt;</pre>

		      <p>where the parameters are in the following form:</p>

		      <ul>
		        <li><code>user</code> contains the users ID</li>
		        <li><code>restaurant</code> contains the restaurants ID</li>
		      </ul>

		      <p>Certain parameters are required in the request's body.</p>

		      <p><strong>Request Body</strong></p>
		      
		      <ul>
		        <li><code>device</code> - the device_id of the device making the request.</li>
		        <li><code>reports</code> - a list of reports as a JSON string.</li>
		      </ul>

		      <p><strong>Reports</strong></p>

		      <p>A JSON string in the following format:</p>

		      <pre>[
  {"when": "2015-01-08 01:42:46 UTC", "preptime": 5490},
  {"when": "2015-01-09 01:42:46 UTC", "preptime": 2344},
		  ...
]</pre>

		      <p>Each activity has the following properties:</p>

		      <ul>
		        <li><code>date</code> - A date string in the format YYYY-MM-DD.</li>
		        <li><code>value</code> - A number value.</li>
		      </ul>

		      <p><strong>Response</strong></p>

		      <p>A successful POST request will return a JSON object with the following properties</p>

		      <ul>
		        <li><code>success</code> - True or False, depending on whether it was successful</li>
		        <li><code>key</code> - If the request was successful, this is the alphanumeric key of the new activity</li>
		      </ul>

		      <p>Example:</p>

		      <pre>{
"success": true,
"key": "..."
}</pre>

		    </div>

		    <div class="span6">

		      <div class="page-header">
		        <h1>Test</h1>
		      </div>

		      <p>You can test the API by using the form below. Fill in the <strong>User ID</strong> and <strong>Restaurant ID</strong> for the restaurant you want to submit to.</p>
				<%= render :partial => 'form' %>

		    </div>

		  </div>
 

app/views/reports/new.html.haml
- model_class = Report
.row-fluid
  .span6
    .page-header
      %h1 Adding a Report
    %p Adding a report is done through an HTTP URL in the following form:
    %pre http://cheftab-demo.appspot.com/reports/&lt;user&gt;/&lt;restaurant&gt;
    %p where the parameters are in the following form:
    %ul
      %li
        %code user
        contains the users ID
      %li
        %code restaurant
        contains the restaurants ID
    %p Certain parameters are required in the request's body.
    %p
      %strong Request Body
    %ul
      %li
        %code device
        \- the device_id of the device making the request.
      %li
        %code reports
        \- a list of reports as a JSON string.
    %p
      %strong Reports
    %p A JSON string in the following format:
    %pre
      :preserve
        [
          {"when": "2015-01-08 01:42:46 UTC", "preptime": 5490},
          {"when": "2015-01-09 01:42:46 UTC", "preptime": 2344},
        		  ...
        ]    %p Each activity has the following properties:
    %ul
      %li
        %code date
        \- A date string in the format YYYY-MM-DD.
      %li
        %code value
        \- A number value.
    %p
      %strong Response
    %p A successful POST request will return a JSON object with the following properties
    %ul
      %li
        %code success
        \- True or False, depending on whether it was successful
      %li
        %code key
        \- If the request was successful, this is the alphanumeric key of the new activity
    %p Example:
    %pre
      :preserve
        {
        "success": true,
        "key": "..."
        }  .span6
    .page-header
      %h1 Test
    %p
      You can test the API by using the form below. Fill in the
      %strong User ID
      and
      %strong Restaurant ID
      for the restaurant you want to submit to.
    = render :partial => 'form'

app/views/reports/show.html.haml
- model_class = Report
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:device_id)
      \:
  %dd= @report.device_id
  %dt
    %strong
      = model_class.human_attribute_name(:when)
      \:
  %dd= @report.when
  %dt
    %strong
      = model_class.human_attribute_name(:preptime)
      \:
  %dd= @report.preptime
  %dt
    %strong
      = model_class.human_attribute_name(:restaurant_id)
      \:
  %dd= @report.restaurant_id
  %dt
    %strong
      = model_class.human_attribute_name(:user_id)
      \:
  %dd= @report.user_id
  %p= debug(@json)
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    reports_path, :class => 'btn'                            |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_report_path(@report), :class => 'btn'               |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    report_path(@report),                                                                                        |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |

app/views/reports/success.html.haml
= debug(params)
= link_to "<- Back", :back